// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkUpyndh3rV-3WVIB1qxFviStrX3H-d9E',
    appId: '1:805852120607:web:f0f0fe62712c728010b72a',
    messagingSenderId: '805852120607',
    projectId: 'agricultural-guide-app',
    authDomain: 'agricultural-guide-app.firebaseapp.com',
    storageBucket: 'agricultural-guide-app.firebasestorage.app',
    measurementId: 'G-R6QEYEDF2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALPs8qCZXBADrfD5FA1RphrOYAnKIFvtc',
    appId: '1:805852120607:android:ffbe49f4253a6b4110b72a',
    messagingSenderId: '805852120607',
    projectId: 'agricultural-guide-app',
    storageBucket: 'agricultural-guide-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN53kPtYN1ORuksQivZ5yu3tKFpkjhshQ',
    appId: '1:805852120607:ios:bc937eb5970b73a410b72a',
    messagingSenderId: '805852120607',
    projectId: 'agricultural-guide-app',
    storageBucket: 'agricultural-guide-app.firebasestorage.app',
    iosBundleId: 'com.example.agriculturalGuideApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkUpyndh3rV-3WVIB1qxFviStrX3H-d9E',
    appId: '1:805852120607:web:e7434109a13ba07b10b72a',
    messagingSenderId: '805852120607',
    projectId: 'agricultural-guide-app',
    authDomain: 'agricultural-guide-app.firebaseapp.com',
    storageBucket: 'agricultural-guide-app.firebasestorage.app',
    measurementId: 'G-B62LETBWVG',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN53kPtYN1ORuksQivZ5yu3tKFpkjhshQ',
    appId: '1:805852120607:ios:bc937eb5970b73a410b72a',
    messagingSenderId: '805852120607',
    projectId: 'agricultural-guide-app',
    storageBucket: 'agricultural-guide-app.firebasestorage.app',
    iosBundleId: 'com.example.agriculturalGuideApp',
  );

}